language: python
cache: pip
python:
- 3.7.8
- 3.8
- 3.9
jobs:
  include:
    - name: "Python 3.10"
      dist: jammy  # Ubuntu 22.04
      python: "3.10"
      before_install:
       # https://discourse.charmhub.io/t/cannot-install-dependencies-modulenotfounderror-no-module-named-setuptools-command-build/7374
       - pip install wheel==0.37.1
       - pip install setuptools==45.2.0
env:
  global:
  - PYTHONPATH=.
install:
- pip install coverage
- pip install coveralls
- pip install -r tests/requirements.txt
- cp packaging/setup.py .
- pip install .
script:
- python -u -m unittest discover -v tests
after_success:
- coverage run --rcfile=tests/.coveragerc -m unittest discover -v tests
- coveralls
