language: python
cache: pip
jobs:
  include:
    - name: "Python 3.7.8"
      python: 3.7.8
    - name: "Python 3.8"
      python: "3.8"
    - name: "Python 3.9"
      python: "3.9"
    - name: "Python 3.10"
      dist: jammy  # Ubuntu 22.04
      python: "3.10"
      before_install:
        - pip3 install --upgrade setuptools
env:
  global:
  - PYTHONPATH=.
install:
- pip install coverage
- pip install coveralls
- pip install -r tests/requirements.txt
- cp packaging/setup.py .
- pip install .
script:
- python -u -m unittest discover -v tests
after_success:
- coverage run --rcfile=tests/.coveragerc -m unittest discover -v tests
- coveralls
